steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dataflow-images/dataflow-pubsub-windowing:latest', '.']

# Step 2: Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/dataflow-images/dataflow-pubsub-windowing:latest']

# Step 3: Run Dataflow Job
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gcloud'
    - 'dataflow'
    - 'flex-template-run'
    - 'job-posting-ingestion'
    - '--template-file-gcs-location=gs://dataflow-templates/latest/flex/PubSub_to_BigQuery'
    - '--region=us-central1'
    - '--parameters'
    - 'inputTopic=projects/$PROJECT_ID/topics/job-postings,outputTable=$PROJECT_ID:labour_market.raw_job_posting'
